language: go
sudo: false
go:
  - 1.10.x
  - master

install:
  - go mod download
  - go get github.com/bookerzzz/gocovmerge

script:
  - make test
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
