language: go
go:
 - 1.7.x
 - master

 env:
   global:
   - CODECOV_TOKEN="1aadcc31-9144-4a63-b4b2-4f2af3222d41"

addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide

install:
  - glide install
  - go get github.com/bookerzzz/gocovmerge

script:
 - make test
 - set -e make cover
